{
 "title": "FreeSwitch",
 "tags": [
  "freeswitch",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(freeswitch_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "基本信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "运行状态",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_uptime_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_current_idle_cpu{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "最大会话数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_max_sessions{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "最大SPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_max_sps{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "处理的会话总数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_sessions_total {instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "注册信息",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_registrations{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "会话信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "当前会话数",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_current_sessions{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "近5分钟峰值会话数",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_current_sessions_peak_last_5min{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "峰值会话数",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_current_sessions_peak{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "当前SPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_current_sps{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "近5分钟峰值SPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_current_sps_peak_last_5min{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "峰值SPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeswitch_current_sps_peak{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "运行状态",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "当前会话数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "freeswitch_current_sessions{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "每秒处理会话数(SPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "freeswitch_current_sps{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "freeswitch_current_idle_cpu{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Bridged Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "freeswitch_bridged_calls{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "freeswitch_current_calls{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Detailed Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "freeswitch_detailed_calls{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "网关信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Gateway Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_sofia_gateway_status{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Gateway Ping",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_sofia_gateway_ping{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Gateway Call In",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_sofia_gateway_call_in{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Gateway Call Out",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_sofia_gateway_call_out{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Gateway Failed Call In",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_sofia_gateway_failed_call_in{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Gateway Failed Call Out",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_sofia_gateway_failed_call_out{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "模块信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Modules Stauts",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_load_module{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "编码状态",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Codec",
     "type": "stat",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_codec_status{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Endpoint Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Endpoint",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_endpoint_status{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Verto Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Verto",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freeswitch_verto_status{instance=\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}